# Generated by Django 5.1.4 on 2025-04-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='special_requests',
            new_name='special_instructions',
        ),
    ]
