# Generated by Django 5.1.4 on 2025-04-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_special_requests_orderitem_special_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='special_instructions',
            new_name='special_requests',
        ),
    ]
