# Generated by Django 5.1.4 on 2025-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='main_app.promotion'),
        ),
    ]
